apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photo-album-certificate
  namespace: {{ namespace }}
spec:
  secretName: photo-album-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}