apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photo-album-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: photo-album-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - backend:
              service:
                name: photo-album-service
                port:
                  name: springboot-port
            pathType: ImplementationSpecific