apiVersion: v1
kind: Service
metadata:
  name: photo-album-service
  namespace: {{ namespace }}
spec:
  selector:
    app: photo-album
    branch: {{ git_branch }}
  ports:
    - port: 8080
      name: springboot-port