- set_fact:
    config_values:
        LOCAL_STORAGE_BASE_PATH: "{{ pod_images_mount_path }}"
        DATABASE_URL: jdbc:postgresql://server.internal.ruchij.com:5420/photo-album
    secrets:
        DATABASE_USER: "{{ lookup('aws_ssm', '/photo-album/database/user', region='ap-southeast-2') }}"
        DATABASE_PASSWORD: "{{ lookup('aws_ssm', '/photo-album/database/password', region='ap-southeast-2') }}"
        AUTHENTICATION_SECRET: "{{ lookup('aws_ssm', '/photo-album/authentication-secret', region='ap-southeast-2') }}"