- set_fact:
    config_values:
        LOCAL_STORAGE_BASE_PATH: "{{ pod_images_mount_path }}"
    secrets:
        AUTHENTICATION_SECRET: "{{ lookup('aws_ssm', '/photo-album/authentication-secret', region='ap-southeast-2') }}"